id = "swift-syntax"
name = "Swift Syntax"
description = "Swift syntax highlighting support."
version = "0.4.0"
schema_version = 1
authors = [
    "ejjonny <https://github.com/ejjonny>",
    "Samuser107 L.Longheval <samuser107@gmail.com>",
    "Kirow <https://github.com/kirow>",
]
repository = "https://github.com/Kirow/zed-swift-highlight.git"

[grammars.swift]
repository = "https://github.com/alex-pinkus/tree-sitter-swift"
commit = "33e56e4e2a6455f3fd4e04cfe5c7a314d498612d"
